import { path } from "@keyma/core/util";
import type { EmitFile } from "@keyma/compiler";
import type { JsEmitterPack } from "@keyma/compiler/backend-js";
import { UI_DOMAIN, readUiExtension, viewsJson } from "../extension.js";

const VIEWS_DTS = `// Generated by @keyma/ui — UI view metadata. Do not edit.
export interface UiWidget { field: string; kind: string; }
export interface UiView { name: string; title: string; route: string; widgets: UiWidget[]; }
export declare const views: UiView[];
`;

/**
 * The UI-domain JS emitter pack. It provides no `buildSchemaData` (the schema domain owns the
 * per-schema metadata); it only implements the multi-pack `emitBundleFiles` hook, contributing
 * `ui/views.{js,d.ts}` derived from `ir.extensions['ui']`. Because it touches none of the
 * schema files, adding it to a bundle leaves all schema output byte-identical.
 */
export const uiJsEmitterPack: JsEmitterPack = {
    name: UI_DOMAIN,
    emitBundleFiles: (ir, ctx): EmitFile[] => {
        const ext = readUiExtension(ir);
        if (ext === undefined || ext.views.length === 0) return [];
        const js = `// Generated by @keyma/ui — UI view metadata. Do not edit.\nexport const views = ${viewsJson(ext)};\n`;
        return [
            { path: path.posix.join(ctx.bundleDir, "ui", "views.js"), content: js },
            { path: path.posix.join(ctx.bundleDir, "ui", "views.d.ts"), content: VIEWS_DTS },
        ];
    },
};
