import { path } from "@keyma/core/util";
import type { EmitFile } from "@keyma/compiler";
import type { CppEmitterPack } from "@keyma/compiler/backend-cpp";
import { UI_DOMAIN, readUiExtension, viewsJson } from "../extension.js";

/**
 * The UI-domain C++ emitter pack. It omits the schema-metadata + enum hooks (now optional on
 * `CppEmitterPack`) and implements only the multi-pack `emitBundleFiles` hook, contributing
 * `ui/views.hpp` derived from `ir.extensions['ui']` — the view JSON embedded as a raw string
 * literal. Schema/enum output stays byte-identical.
 */
export const uiCppEmitterPack: CppEmitterPack = {
    name: UI_DOMAIN,
    emitBundleFiles: (ir, ctx): EmitFile[] => {
        const ext = readUiExtension(ir);
        if (ext === undefined || ext.views.length === 0) return [];
        const hpp =
            `#pragma once\n` +
            `// Generated by @keyma/ui — UI view metadata. Do not edit.\n` +
            `namespace keyma_ui {\n` +
            `inline constexpr const char* views_json = R"json(\n${viewsJson(ext)}\n)json";\n` +
            `}\n`;
        return [{ path: path.posix.join(ctx.bundleDir, "ui", "views.hpp"), content: hpp }];
    },
};
