import { path } from "@keyma/core/util";
import type { EmitFile } from "@keyma/compiler";
import type { PythonEmitterPack } from "@keyma/compiler/backend-python";
import { UI_DOMAIN, readUiExtension, viewsJson } from "../extension.js";

/**
 * The UI-domain Python emitter pack. No `buildSchemaData` (the schema domain owns metadata);
 * it implements only the multi-pack `emitBundleFiles` hook, contributing `ui/views.py` (plus
 * the package `ui/__init__.py`) derived from `ir.extensions['ui']`. The view JSON contains only
 * strings/lists/objects, so it is a valid Python literal. Schema output stays byte-identical.
 */
export const uiPythonEmitterPack: PythonEmitterPack = {
    name: UI_DOMAIN,
    emitBundleFiles: (ir, ctx): EmitFile[] => {
        const ext = readUiExtension(ir);
        if (ext === undefined || ext.views.length === 0) return [];
        const py = `# Generated by @keyma/ui — UI view metadata. Do not edit.\nviews = ${viewsJson(ext)}\n`;
        return [
            { path: path.posix.join(ctx.bundleDir, "ui", "__init__.py"), content: "" },
            { path: path.posix.join(ctx.bundleDir, "ui", "views.py"), content: py },
        ];
    },
};
